# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Digest-MD5-M4p
version:      0.01
version_from: M4p.pm
installdirs:  perl
requires:
    Digest::base:                  1.00
    File::Spec:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
